import type { Metadata } from "next";
import { Montserrat, Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { shadcn } from "@clerk/themes";

const montserrat = Montserrat({ subsets: ["latin"], variable: "--font-montserrat" });
const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ExecOS",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      lang="en"
      className={`${montserrat.variable} ${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-screen w-full relative">
        <ClerkProvider
          appearance={{
            baseTheme: shadcn,
            variables: {
              colorPrimary: "oklch(0.6 0.2 25)",
              colorPrimaryForeground: "#ffffff",
              colorBackground: "oklch(0.15 0.005 280)",
              colorForeground: "#ffffff",
              colorInputForeground: "#ffffff",
              colorNeutral: "#ffffff",
              colorMutedForeground: "#ffffff",
              borderRadius: "0.625rem",
            },
          }}
        >
          {children}
        </ClerkProvider>
      </body>
    </html>
  );
}